[unstable]
#build-std = ["core"]
#build-std-features = ["panic_immediate_abort"]

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip nrf5340_xxAA_net"

rustflags = [
  # Code-size optimizations.
  "-C", "force-frame-pointers=yes",
]

[build]
target = "thumbv8m.main-none-eabi"

[env]
DEFMT_LOG = "info"
